spring.application.name=lhims
spring.config.import=optional:file:.env[.properties]

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5400}/${DB_NAME:lhims_db}
spring.datasource.username=${DB_USER:lhims_user}
spring.datasource.password=${DB_PASS:lhims_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-migration-naming=true
spring.flyway.clean-disabled=true
